name: Deploy via ftp
on: 
  push:
    branches: 
      - main
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: FTP Deploy Locaweb
      uses: locaweb/ftp-deploy@1.0.0
      with:
        host: ftp.ativisoft.com.br
        user: ativisoft1
        password: GGA@20002021gftp
        remoteDir: public_html